"""empty message

Revision ID: 22b1ff6ded75
Revises: f8501618adf7
Create Date: 2024-05-28 16:24:00.307277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b1ff6ded75'
down_revision = 'f8501618adf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_column('dog_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dog_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('breed',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
