"""empty message

Revision ID: 6c7894157b64
Revises: e2308c8b554b
Create Date: 2024-05-17 10:14:09.004364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7894157b64'
down_revision = 'e2308c8b554b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('breed_1_img_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('breed_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('breed_2_img_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('breed_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('breed_3_img_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('breed_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('breed_4_img_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('breed_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('breed_5_img_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('breed_5_img_url')
        batch_op.drop_column('breed_5')
        batch_op.drop_column('breed_4_img_url')
        batch_op.drop_column('breed_4')
        batch_op.drop_column('breed_3_img_url')
        batch_op.drop_column('breed_3')
        batch_op.drop_column('breed_2_img_url')
        batch_op.drop_column('breed_2')
        batch_op.drop_column('breed_1_img_url')
        batch_op.drop_column('breed_1')

    # ### end Alembic commands ###
