"""empty message

Revision ID: 73a8d9568d5a
Revises: 946aca45aa3e
Create Date: 2024-05-15 14:24:51.872683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a8d9568d5a'
down_revision = '946aca45aa3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('l_name', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_f_name_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.create_unique_constraint('user_f_name_key', ['f_name'])
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('l_name')

    # ### end Alembic commands ###
