"""empty message

Revision ID: ae7df5d6ee87
Revises: 
Create Date: 2024-05-14 12:01:07.632897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7df5d6ee87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.String(length=50), nullable=False),
    sa.Column('org_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dog_url', sa.String(length=200), nullable=False),
    sa.Column('age', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('city_state', sa.String(length=100), nullable=False),
    sa.Column('dog_zip_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('user_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=False),
    sa.Column('breed_1', sa.String(length=100), nullable=False),
    sa.Column('breed_1_img', sa.String(length=200), nullable=False),
    sa.Column('breed_2', sa.String(length=100), nullable=False),
    sa.Column('breed_2_img', sa.String(length=200), nullable=False),
    sa.Column('breed_3', sa.String(length=100), nullable=False),
    sa.Column('breed_3_img', sa.String(length=200), nullable=False),
    sa.Column('breed_4', sa.String(length=100), nullable=False),
    sa.Column('breed_4_img', sa.String(length=200), nullable=False),
    sa.Column('breed_5', sa.String(length=100), nullable=False),
    sa.Column('breed_5_img', sa.String(length=200), nullable=False),
    sa.Column('breed_6', sa.String(length=100), nullable=False),
    sa.Column('breed_6_img', sa.String(length=200), nullable=False),
    sa.Column('breed_7', sa.String(length=100), nullable=False),
    sa.Column('breed_7_img', sa.String(length=200), nullable=False),
    sa.Column('breed_8', sa.String(length=100), nullable=False),
    sa.Column('breed_8_img', sa.String(length=200), nullable=False),
    sa.Column('breed_9', sa.String(length=100), nullable=False),
    sa.Column('breed_9_img', sa.String(length=200), nullable=False),
    sa.Column('breed_10', sa.String(length=100), nullable=False),
    sa.Column('breed_10_img', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('f_name'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dog')
    # ### end Alembic commands ###
