"""empty message

Revision ID: e4df8f6cdc78
Revises: 
Create Date: 2024-05-14 14:48:35.419333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4df8f6cdc78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('api_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adoption_url', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('fb_url', sa.String(length=200), nullable=True),
    sa.Column('org_zip_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('user_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('f_name'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dog',
    sa.Column('api_id', sa.String(length=50), nullable=False),
    sa.Column('org_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dog_url', sa.String(length=200), nullable=True),
    sa.Column('age', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('city_state', sa.String(length=100), nullable=True),
    sa.Column('dog_zip_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.api_id'], ),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_table('fav_dog',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.api_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'dog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_dog')
    op.drop_table('dog')
    op.drop_table('user')
    op.drop_table('org')
    # ### end Alembic commands ###
